### ISSUE TITLE
express-server task does not appear to kill/restart node app properly

### ISSUE THREAD

**Issue by kwhitley** [ericclemmons/genesis-skeleton#10]
Found by changing a registered route after the watch changes are enabled.  The watch task triggers, browser reload occurs as required, but the route is left unchanged.

Assuming this is because the original app is left running instead of killed/reloaded...

**Comment by ericclemmons** [comment]
Right, this functionality isn't supported just yet, as restarting a node server vs. a built resource was considerably trickier :)

**Comment by kwhitley** [comment]
Grrr.

**Comment by ericclemmons** [comment]
I think I have this worked on... PR soon!
