### ISSUE TITLE
Occasional fail on live reload 

### ISSUE THREAD

**Issue by facultymatt** [ericclemmons/genesis-skeleton#100]
Occasionally, when I saving a file and grunt rebuild / reloads, I get the following error: 

```
Assertion failed: (stream->write_queue_size == 0), function uv__write, file ../deps/uv/src/unix/stream.c, line 726.
No captured browser, open http://localhost:9876/
```

The causes localhost:3000 to be unavailable (although the server still appears to be running). To fix this I must stop the server and run `grunt server` again.

**Comment by ericclemmons** [comment]
Wow, I've yet to see that!  Does it happen early in the session, or after prolonged use for you?

Also, what system are you on?

**Comment by facultymatt** [comment]
I'll send over more details later, for now you can recreate by doing the following:
1. run `grunt server` and visit localhost:3000
2. activate live reload
3. save a change, so live reload tirggers
4. make a change that will fail jshint, ex: delete a semi colon 
5. save, you should get a log like the log below
6. then fix this change and save again.
7. All sorts of strange things start happening...

> > Running "jshint:files" (jshint) task
> > Linting client/app/scripts/app.js...ERROR
> > [L100:C5] Expected ')' and instead saw ';'.
> >     ;
> > [L100:C6] Missing semicolon.
> >     ; 
> > 
> > Warning: Task "jshint:files" failed. Use --force to continue.
> > 
> > Aborted due to warnings.

Running "copy:js" (copy) task
Copied 22 files

Running "parallel:jshint" (parallel) task

Running "livereload" task
... Reload build/app/scripts/services/user.js ...

Running "karma:background:run" (karma) task
Assertion failed: (stream->write_queue_size == 0), function uv__write, file ../deps/uv/src/unix/stream.c, line 726.
Abort trap: 6

**Comment by ericclemmons** [comment]
AWESOME, I can work with that!  Thank you!

**Comment by facultymatt** [comment]
Any progress on this? Now getting it slightly different, on Regrade instead of karma: 

```
Running "regarde" task
Assertion failed: (stream->write_queue_size == 0), function uv__write, file ../deps/uv/src/unix/stream.c, line 726.
Abort trap: 6
```

**Comment by ericclemmons** [comment]
I've had people tell me that regarde is slowly getting less reliable with grunt & newer versions of node.  What sucks is the last time I tried to use `grunt-contrib-watch`, it did this massive reload on the page, rather than just the file that changed, as expected.

That error you're getting _is_ similar to one I've gotten when running the server for long periods of time...

**Comment by ericclemmons** [comment]
@facultymatt Can you check out `master`?  I'm using `grunt-contrib-watch` now, and would like to resolve any lingering issues...

**Comment by facultymatt** [comment]
I'll check it out later today. Off the grid now. 
—

**Comment by facultymatt** [comment]
@ericclemmons this isn't working consistently for me. Checked out master, started 'grunt server', made a change to home.js and saved... the server stopped with the following logs: 

```
Running "watch" task
Waiting...GET / 200 14ms
GET /app/scripts/services/api.js 200 17ms
GET /bower_components/modernizr/modernizr.js 200 19ms
GET /app/scripts/app.js 200 17ms
GET /app/scripts/controllers/home.js 200 19ms
GET /app/styles/app.css 200 28ms
GET /bower_components/angular/angular.js 200 57ms
GET /app/scripts/app.templates.js 200 4ms
GET /api/bower 200 90ms - 286b
GET /api/package 200 28ms - 1.42kb
GET /favicon.ico 404 10ms
OK
>> File "client/app/scripts/controllers/home.js" changed.


Running "copy:js" (copy) task
Copied 6 files

Running "jshint:files" (jshint) task
>> 9 files lint free.

Running "karma:background:run" (karma) task
There is no server listening on port 9100

Running "watch" task
Completed in 0.220s at Sat Jul 06 2013 10:06:33 GMT-0400 (EDT) - Waiting...

Done, without errors.
Stopping Express server
```

Not sure whats happening. The logs `completed in...` & `Done, without errors.` happen just about every time I save. @note im using node --version 0.10.8 (current is 0.10.10) but I doubt this would be the cause of the issue.

I'll play around with the gruntfile and try to figure out whats happening.

**Comment by ericclemmons** [comment]
Got the same issue last night, it's because I accidentally left in `karma:background:run`.  Simple fix, just pull it out of the appropriate `watch` task.

**Comment by ericclemmons** [comment]
Check out the [feature/react](https://github.com/ericclemmons/genesis-skeleton/tree/feature/react) branch for some of the latest changes I've been making to work well with React.  One, it's using a new version of Karma, which should remove the need for `grunt server:unit`, since Karma can watch files fine on it's own, but it also requires redoing how angular modules are declared.  (Each file needs to live in its own namespace, not expect `app` to pre-exist).

**Comment by ericclemmons** [comment]
Fixed this bug.  Also, clearing out issues because of tons of sweeping changes to the codebase.  Karma is proving fickle, and we need a fresh start...
