### ISSUE TITLE
Incorrect package.json

### ISSUE THREAD

**Issue by facultymatt** [ericclemmons/genesis-skeleton#103]
line: https://github.com/ericclemmons/genesis-skeleton/blob/master/package.json#L43 should be 

`"grunt-contrib-mincss": "~0.4.0-rc7",`

you forgot the `-`

**Comment by ericclemmons** [comment]
Oh!  How in the heck did this thing install!?

Thanks!

**Comment by facultymatt** [comment]
You prob did a terminal `bower install grunt-contrib-mincss` install, then went back after the fact and added to the bower file. I've done this myself before and didn't catch the incorrect bower.json addition because I had already installed the bower package. ;)

**Comment by ericclemmons** [comment]
Fixed via #106!
