### ISSUE TITLE
Incorrect bower setup

### ISSUE THREAD

**Issue by facultymatt** [ericclemmons/genesis-skeleton#104]
You are pointing to `bower_components/...` for bower files... however bower is currently configured to compile to `components/...`

By default bower installs into components, to over-ride this you'll need a bower config file... but this doesn't appear to be committed in master... unless I'm missing something. Did you change this manually? 

To fix, I suggest either: 
1. commit the `.bowerrc` config file
2. change references to components to work with default install

**Comment by ericclemmons** [comment]
Bower updated to `v0.10.x` recently, which changed the location.  If you do `npm update -g bower`, it should install the new version.

Do you know of another way of forcing this version, since bower is expected to be globally installed?

**Comment by facultymatt** [comment]
Not sure there's a way to do this... I'll do some research. 

Short term (and maybe the best option) is a changelog... for each version list a summary of changes, bug fixes, features, etc. Highlight Breaking changes and NPM commands to run.

**Comment by ericclemmons** [comment]
I'll add this to the README for now.  I guess I reinstall Bower all the time :D
