### ISSUE TITLE
Coffescript for Server code

### ISSUE THREAD

**Issue by matthias** [ericclemmons/genesis-skeleton#117]
If you update grunt-express-server to ~0.4.0 you could use coffeescript also for server side code

@see https://github.com/rehno-lindeque/grunt-express-server/commit/33171d6f7d06f9c3b7426e3d81e206fd48b24bf0

``` coffeescript
    # Express requires `server.script` to reload from changes
    express:
      server:
        options:
          cmd:        'coffee'
          script:     '<%= SERVER_DIR %>/server.coffee'
```

**Comment by ericclemmons** [comment]
Man, you're right.  I've spent so much time on https://github.com/genesis/wordpress that this project is in need of updates from my other projects :(
