### ISSUE TITLE
HTML in public folder not accessible on existing browser port...

### ISSUE THREAD

**Issue by kwhitley** [ericclemmons/genesis-skeleton#18]
Appears to be a content decoding issue - perhaps with express static or gzippo?

Only appears to affect the proxy port from grunt-reload.  Content length is zero on gzipped html for some reason (on proxy).

**Comment by ericclemmons** [comment]
To replicate this, rename `humans.txt` to `humans.html`, then open: http://localhost:8000/humans.html

Changing out the following fixes it:

``` js
// src/server/app.js
23 app.use(express.static(path.join(__dirname, '../../public')));
24 // app.use(gzippo.compress());
```

**Comment by ericclemmons** [comment]
Issue found & documented here: https://github.com/webxl/grunt-reload/issues/20

**Comment by ericclemmons** [comment]
Solving this via b2f09021cfedd7f462bf6fac4bc1bba0f0293e0a & #29
