### ISSUE TITLE
Use H5BP for Node

### ISSUE THREAD

**Issue by ericclemmons** [ericclemmons/genesis-skeleton#19]
See the latest code here, which _should_ work via `app.use(require('h5bp'))`.

> https://github.com/h5bp/server-configs/blob/master/node/lib/h5bp.js

The problem is NPM has a **10 month old version**:

> https://github.com/h5bp/server-configs

I dunno if we can just do `*` rather than `0.0.2` and pull `master`, but the latest code _seems_ like it should work.

**Comment by ericclemmons** [comment]
Also, another consideration is that perhaps we use the entirety of the source code, since it _is_ meant for modifications, at least on Apache, which would bypass all of these issues.

**Comment by ericclemmons** [comment]
Awaiting some sort of response on https://github.com/h5bp/server-configs/issues/55.  If nothing, we might create our middleware to add sane-defaults for cache times on images, etc.

**Comment by ericclemmons** [comment]
Tired of waiting.  Going to close until there's a problem.

**Comment by niftylettuce** [comment]
hey sorry about this, been very busy, working on it now.

**Comment by ericclemmons** [comment]
Haha, it's ok :)  I just closed this issue here so we wouldn't have to delay our 1.0 release.

**Comment by niftylettuce** [comment]
@ericclemmons can you test this out? https://github.com/niftylettuce/node-h5bp  -- I also just pushed v0.0.3 to NPM
