### ISSUE TITLE
Switch to Jade

### ISSUE THREAD

**Issue by ericclemmons** [ericclemmons/genesis-skeleton#2]
TJ Hollawaychuk finds EJS buggy and defaults to Jade for ExpressJS.

I think it's best to use the defaults of the library/tool authors rather than imposing a different requirement for my own convenience.

**Comment by ericclemmons** [comment]
@kwhitley Screw it.  Jade sucks, namely for debugging:

> https://github.com/visionmedia/jade/issues/252

So, I'm going to use Handlebars instead:

> https://npmjs.org/package/express3-handlebars

To be honest, I'm not quite sure I like _any_ templating solutions outside of Angular.  Also, my opinion of using `usemin` may have changed a bit.  The fact of the matter is, you **will** have to hand-code your layout a bit to include the right CSS & JS.  As in, you may want to separate all of your JS libs from your app (like we talked today), but compile the CSS as one.  Personal preference.

The annoyance with most templating engines I've seen so far is that they don't let you use Javascript expressions, aside from EJS, which doesn't support inheritance.

Ugh...

**Comment by kwhitley** [comment]
No line numbers???

![jade](http://citynoise.org/upload/31181.jpg)

**Comment by ericclemmons** [comment]
Maybe [Twig.js](https://github.com/justjohn/twig.js)?

**Comment by kwhitley** [comment]
That's my vote - this was barely implemented last time I looked (no
blocks/include among other things), so JinJS was preferable, but it looks
like this has finally caught up (and is far easier to implement).

:+1:
