### ISSUE TITLE
Getting Error: listen EADDRINUSE

### ISSUE THREAD

**Issue by jonphipps** [ericclemmons/genesis-skeleton#31]
Just tried the a fresh install (comparing it to the new Yeoman skeleton) and I'm getting this error. I've checked to make sure nothing else is listening on 8000 and there isn't even another instance of node running. I'm not 100% sure it's really an issue with your code, but it looks a lot like the server's being run twice. 

``` bash
Running "watch" task
Waiting...Express server listening on port 8000

events.js:71
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: listen EADDRINUSE
    at errnoException (net.js:770:11)
    at Server._listen2 (net.js:910:14)
    at listen (net.js:937:10)
    at Server.listen (net.js:986:5)
    at Function.app.listen (~/sites/genesis-skeleton/node_modules/grunt-reload/node_modules/connect/lib/proto.js:229:24)
    at Object.module.exports (~/sites/genesis-skeleton/node_modules/grunt-reload/tasks/reload.js:190:54)
    at Object.task.registerTask.thisTask.fn (~/sites/genesis-skeleton/node_modules/grunt/lib/grunt/task.js:58:16)
    at Task.<anonymous> (~/sites/genesis-skeleton/node_modules/grunt/lib/util/task.js:343:36)
    at Task.<anonymous> (~/sites/genesis-skeleton/node_modules/grunt/lib/util/task.js:319:9)
    at Task.<anonymous> (~/sites/genesis-skeleton/node_modules/grunt/lib/util/task.js:346:11)
```

**Comment by ericclemmons** [comment]
Hey @jonphipps!  Can you let me know a couple of things?
- Command you used to trigger this command
- `grunt --version`

Thanks!

**Comment by jonphipps** [comment]
Sure!

Ran it with...

``` bash
$ grunt server

$ grunt --version
grunt v0.3.17
```

**Comment by ericclemmons** [comment]
Well, shoot.  Let me see if #36 would resolve this.  I can't reproduce it on my machine, and no one else I pinged could either :(

**Comment by jonphipps** [comment]
I don't know if it'll help any, but here's the rest of the output from running...

``` bash
$ grunt server
Running "lint:files" (lint) task
Lint free.

Running "less:app" (less) task
File public/build/css/app.css created.

Running "ngtemplates:app" (ngtemplates) task
File public/build/js/templates.js created.

Running "concat:angular" (concat) task
File "./public/build//js/lib/angular.js" created.

Running "concat:app" (concat) task
File "./public/build//js/app.js" created.

Running "concat:all" (concat) task
File "./public/build//js/all.js" created.

Running "copy:app" (copy) task
Copying files to public/build/img/...OK

Running "copy:lib" (copy) task
Copying files to public/build/img/...OK

Running "express-server" task

Running "reload" task
reload server running at http://localhost:35729

Running "open:dev" (open) task

Running "watch" task
Waiting...Express server listening on port 8000

events.js:71
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: listen EADDRINUSE
    at errnoException (net.js:770:11)
    at Server._listen2 (net.js:910:14)
    at listen (net.js:937:10)
    at Server.listen (net.js:986:5)
```

Wish I knew more about grunt, express, and nodejs in general to be able to help debug. It seems highly likely that it's something local to my nodejs or Mac Lion environment.

Might it also matter that just before I was trying out Genesis, I was trying out the very new Yeoman Express Stack https://github.com/yeoman/yeoman/tree/express-stack as I mentioned before?

**Comment by ericclemmons** [comment]
Change in `grunt.js` `8000` to `3000`, or `5000` (or anything you'd like :D) and see if `grunt server` runs for you.

My thinking is that I chose a common port, and shouldn't hard-code this by default, since it likely is environment-specific.

I've been trying to make a case for Yeoman for > a month now.  I have lots of experience with generators, and found that the projects that I have (and those of my company) need a solid starting point that's forkable for small variations (such as using Foundation instead of Bootstrap, SCSS instead of LESS, etc.), rather than generating code that doesn't follow our conventions. 

I'll fix up that other issue so this doesn't affect anyone else.

Thanks again for the feedback & the issue @jonphipps!

**Comment by ericclemmons** [comment]
Also, here's my output:

``` sh
 ~ ⮁ Sites ⮁ ericclemmons ⮁ genesis-skeleton ⮀ master ⮀ $ ⮀grunt server
Running "lint:files" (lint) task
Lint free.

Running "less:app" (less) task
File public/build/css/app.css created.

Running "ngtemplates:app" (ngtemplates) task
File public/build/js/templates.js created.

Running "concat:angular" (concat) task
File "./public/build//js/lib/angular.js" created.

Running "concat:app" (concat) task
File "./public/build//js/app.js" created.

Running "concat:all" (concat) task
File "./public/build//js/all.js" created.

Running "copy:app" (copy) task
Copying files to public/build/img/...OK

Running "copy:lib" (copy) task
Copying files to public/build/img/...OK

Running "express-server" task

Running "reload" task
reload server running at http://localhost:35729

Running "open:dev" (open) task

Running "watch" task
Waiting...Express server listening on port 8000
GET / 304 25ms
GET /build/js/app.js?v=0.0.1 200 6ms
GET /build/css/app.css?v=0.0.1 200 9ms
GET /build/img/overlay-dot.png 200 3ms - 118
GET /build/img/background.jpg 200 4ms - 56.94kb
```

**Comment by ericclemmons** [comment]
#36 has been resolved.  This will use whichever port you like, or fall back to 3000 like most node apps:

> `PORT=12345 grunt server`
