### ISSUE TITLE
Complete genesis-skeleton.com + documentation

### ISSUE THREAD

**Issue by ericclemmons** [ericclemmons/genesis-skeleton#33]
# Genesis Skeleton

Zero to Live in minutes
## Description

An opinionated modern application starter using the latest technologies (such as Express, Angular, Bootstrap & Grunt) to help you quickly build your next great app.
## Features
- Clear folder structure - Based on both client & server-side convention, every part of your application has a home.
- Automation - Leveraging Grunt, everything from linting your scripts to pre-processing your CSS and images is done for you.
- Live development server - Simply run `grunt server` and watch your changes instantly via LiveReload.
- Angular-optimized - Templates are automatically pre-loaded so your app loads instantly without extra requests.
- Production-ready - From CSS pre-processing to image optimization, everything is ready to go with a simple `grunt build`
- Heroku-ready - Even if your live site will be deployed elsewhere, it's a breeze to show off your app to a client with a few keystrokes.
## Get Started in 5 Easy Steps

(Keep what we have)
### Why not Yeoman (or another generator)?

Yeoman is a fantastic generator.  This project is _not_ a generator.  It's an opinionated starter application meant for you to fork, modify, and use with each project you take on.  Generators by design create a limited structure that you immediately have to wrangle to match your own convention and toolset.  Genesis Skeleton aims to create a structure for your front-end app that is well-organized and flexible to match each project's needs.
### Why Angular (and not another framework)?

For robust applications with a lot of moving parts, Angular has shown to support both rapid prototypes and complex applications requiring well-though architecture.

Don't fret, though!  You're only a simple `bower install` away from having your favorite framework ready to use.
### I have a problem!  How do I solve it?

Open an [issue](https://github.com/ericclemmons/genesis-skeleton/issues) or contact me on Twitter: [@ericclemmons](https://twitter.com/ericclemmons).
## Documentation
1. Download or Clone the project
2. Customize to your project
   2.1. Change `package.json`
   2.2. Change `app.'s` with YOUR SECRET
3. Adding & Removing client-side dependencies
   3.1. Removing (go into how to delete things from bower & build scripts)
   3.2. Adding (go into how to add things in bower & build scripts)
4. Adding & Removing server-side dependencies (should just be NPM)
5. Optimizing your CSS & JS
6. Deployment to Heroku

**Comment by ericclemmons** [comment]
@kwhitley Here's a quick pass at what we need.  My question to you is, does the genesis-skeleton site need to really have angular in it at all, or should it just be a simple express server?

**Comment by kwhitley** [comment]
Anyone can set up a simple express server (albeit without some of the nice automation seen here)... so I think angular should be included.  If you want a barebones version we could do that - and then have variants (including angular) as flavors.

**Comment by kwhitley** [comment]
Just more work!

:watch:

**Comment by ericclemmons** [comment]
Note to myself:

> Use a [tree](http://thecodeplayer.com/walkthrough/css3-family-tree) to show the application structure and Bootstrap tooltips to explain each section.

Then again, as neat as that is, a normal tree view with an explanation panel to the right would make it much easier to describe & understand the structure.
