### ISSUE TITLE
Clean up & fix navigation

### ISSUE THREAD

**Issue by kwhitley** [ericclemmons/genesis-skeleton#37]
As **Home** and **Get Started** both do the same thing, I'd recommend simplifying to only **Get Started** (default).

Additionally, highlighting needs to work for Docs and other routes.

**Comment by ericclemmons** [comment]
Related to #38 & #33.  If we use HTML5 routes and finish up the content, then this will be resolved.

**Comment by ericclemmons** [comment]
Resolved with HTML5 templates and `33-docs`
