### ISSUE TITLE
HTML5 routes with Angular

### ISSUE THREAD

**Issue by ericclemmons** [ericclemmons/genesis-skeleton#38]
If an express app only has a single view, all server-side routes should render the app, and angular should take care of the view.

**Comment by kwhitley** [comment]
Sure, but we have that docs module (server side views)...

**Comment by ericclemmons** [comment]
For now, yes, but I'm still up for figuring out how much of the app is going to be angular, and how much is going to be express.

**Comment by ericclemmons** [comment]
Easy via:

``` js
angular
  .module('app', [
    'app.templates',
    'ngResource'
  ])
  .config(['$locationProvider', '$routeProvider', function($location, $router) {
    $location.html5Mode(true);
...
```

**Comment by ericclemmons** [comment]
Ok,before I make this change, **should I**?

What this will force is:
- Express will have to server up the home page for _any_ unknown route (i.e. 404)
- Angular will need to have a 404 Controller & template via `$router.otherwise(...)`

Is this right?  Is this how apps should be built?  I've always hated the `#!` on URLs, but this act of enable HTML5 URL support will draw a line in the sand:
- Angular & the client-side is responsible for all HTML/template views
- Express is responsible for the layout/skeleton & all API hooks

That doesn't sound _bad_ to me at all, and technically it _is_ really bizarre to have both angular views & non-angular views...

**Comment by kwhitley** [comment]
Only bizarre in a site/page where the app IS the site/page.  That's how we appear to be using it here, but others may not do the same...  however, I _think_ that if you don't provide a default route in angular that it might roll back to the server to resolve.  Worth testing!

**Comment by ericclemmons** [comment]
Take care of in `33-docs` branch.  PR pending!
