### ISSUE TITLE
Views are cached between LiveReloads

### ISSUE THREAD

**Issue by ericclemmons** [ericclemmons/genesis-skeleton#39]
@kwhitley says that 6e088319b940c67f8d04f49ea5433b983c3e4392 was working then.

**Comment by kwhitley** [comment]
**Symptoms**
- if editing a view, with or without LiveReload extension running, a manual page refresh in browser does not update the view.  Interestingly though, opening it in a fresh incognito window DOES update it.  Similarly, curl requests each reflect the change.
- this behavior is not specific to views, as a `res.send({ ok: 1 });` type response appears similarly cached
- beyond just views, even adding/modifying routes (which triggers the **watch** and subsequently **express-server** tasks properly) is not reflected in the browser and will return a typical `"Cannot GET [path]"` message.  I assume these reflect properly in curl requests, based on other observed behavior.

**Additional Notes**
- By enabling the reload server proxy layer, these changes ARE refreshable, even if only manually.

**Comment by ericclemmons** [comment]
Screw it.  Reverting 0500e7f (related to #30)....
