### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by ericclemmons** [ericclemmons/genesis-skeleton#40]
@kwhitley 
- Since `components` are front-end related, should I move them to `src/client/components` the same way Yeoman uses `app/components`?  It's trivial to do, and would make pathing easier between `app.less` and others.
- Should `public` be moved to `src/client/public`, or perhaps `src/public`, or `src/server/public`?
- Should `src/server/lib` be cleaned up in any way?

**Comment by kwhitley** [comment]
`src/server/lib` could be turned to components, sure... but I certainly wouldn't move the `public` folder.  Remember, the whole build process is taking things FROM the client folder and building them "offsite" in the public folder...

**Comment by ericclemmons** [comment]
Ok, so `public` statys.  `src/server/lib` should stay lib, because it's for ... libs :)  A recent commit removed the /docs folder (moving everything to Angular!), so the server-side libs are already kind of small.

 I'll move `components` to `src/client/components` ala Yeoman and get everything synced up.

**Comment by ericclemmons** [comment]
Ok, so with `src/client/components`, we need to put the other files in some other folder (`src/client/app/js`)?

**Comment by kwhitley** [comment]
Yeah, they prob should be grouped by app/module like that

**Comment by ericclemmons** [comment]
Taken care of via 498549a132f28bf3b10a22cd6f95a0fc0e6a8a32.
