### ISSUE TITLE
Missing components 

### ISSUE THREAD

**Issue by facultymatt** [ericclemmons/genesis-skeleton#53]
Hello, really nice work here. Trying to install and start grunt server, but I seem to be missing the components... specifically I'm getting the following error: 

`
Running "less:app" (less) task

> > NameError: variable @gray is undefined in src/client/app/less/app.less:14:14
> > 13 body {
> > 14   background: @gray url("../img/background.jpg") no-repeat top center fixed;
> > 15   background-size: cover;
> > `

It seems that bootstrap is missing completely?

**Comment by kwhitley** [comment]
Bootstrap and other deps should be installed by `npm install`, @facultymatt

Still missing after that step?

**Comment by facultymatt** [comment]
Well, kind of. I already ran NPM install. However, I just tried running npm install again, and it installed more stuff - ala the missing components! (Which are managed with bower, so bower needs to be installed first) I had never come across this before. 

Might I suggest updating the documentation to reflect the possible need to run NPM install two times. 

-Thanks! Nice work, again.

**Comment by kwhitley** [comment]
Interesting... I've never run across that even with blowing the project away and restarting more than a few times - I'll have to see if we can recreate this issue.  Ideas @ericclemmons?

> **Side Note** - I hope we an recreate and resolve this... nothing more annoying than having to run a single step twice!

**Comment by facultymatt** [comment]
You likely installed bower globally using npm install bower -g at some
point. In this case I suspect the bower components would be installed on
the first pass.

On Tuesday, January 22, 2013, Kevin Whitley wrote:

> Interesting... I've never run across that even with blowing the project
> away and restarting more than a few times - I'll have to see if we can
> recreate this issue. Ideas @ericclemmons https://github.com/ericclemmons
> ?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ericclemmons/genesis-skeleton/issues/53#issuecomment-12580106.

## 

_Matt Miller
Creative Developer
m *609.335.4417
*twt_ @mattmillerart http://twitter.com/#!/mattmillerart

## 

faculty
_twt_ @facultycreative http://twitter.com/#!/facultycreative
_w_ www.facultycreative.com

2424 E. York Street
Suite 233
Philadelphia Pa. 19125

**Comment by facultymatt** [comment]
Also worth noting as an aside, the `grunt server` command doesn't work unless you install grunt globally. I had to google this, apparently grunt doesn't install shell/ terminal commands unless its a global install. Not sure if the package manager can do this... http://blog.nodejs.org/2011/03/23/npm-1-0-global-vs-local-installation/ might be helpful.

**Comment by ericclemmons** [comment]
Sure enough, `npm install` automatically runs `bower install`, so it should have been done.

Both bower & grunt recommend (via their docs, and even via warnings when installing grunt via NPM!) global installation:

> npm install -g grunt bower

Should this simply be added in README & quick start?

**Comment by kwhitley** [comment]
Well i just uninstalled global bower, grunt, etc... wiped the repo and started over. `npm install` installed everything without a hitch and only needed `npm install grunt-cli -g` to run `grunt server` (which worked first try).  Even bower install was left up to `npm install` and worked fine...

So.... I'm at a loss!

**Comment by kwhitley** [comment]
npm apparantly doesnt need bower installed globally to run `bower install` (just checked this, as it triggers fine despite the lack of global install).

_However_... we need to put it in the docs anyway, as we want it available for installing components via `bower install --save underscore` and the like...

**Comment by facultymatt** [comment]
Ok, I created a new project, ran npm install, same problem. Needed to run it again to get the components. Im including my node log below... maybe you all can spot something odd I'm doing. 

Thanks, -Matt! 

PS - I just noticed the following warning after my install: 
`npm WARN cannot run in wd genesis-skeleton@0.0.1 bower install (wd=/Applications/MAMP/htdocs/fac/genesis2)`

This appears to be the issue... not sure what it means though. 

Matt-Millers-MacBook-Pro-2:genesis2 mmiller001$ sudo npm install
Password:
npm http GET https://registry.npmjs.org/bower/0.6.8
npm http GET https://registry.npmjs.org/express/3.0.5
npm http GET https://registry.npmjs.org/grunt/0.3.17
npm http GET https://registry.npmjs.org/grunt-angular-templates
npm http GET https://registry.npmjs.org/grunt-css/0.3.2
npm http GET https://registry.npmjs.org/grunt-contrib-copy/0.3.2
npm http GET https://registry.npmjs.org/grunt-contrib-less/0.3.2
npm http GET https://registry.npmjs.org/grunt-contrib-clean/0.3.0
npm http GET https://registry.npmjs.org/grunt-contrib-requirejs
npm http GET https://registry.npmjs.org/grunt-open/0.1.0
npm http GET https://registry.npmjs.org/grunt-reload/0.2.0
npm http GET https://registry.npmjs.org/grunt-smushit/0.3.8
npm http GET https://registry.npmjs.org/grunt-usemin
npm http 304 https://registry.npmjs.org/grunt-angular-templates
npm http 304 https://registry.npmjs.org/bower/0.6.8
npm http 304 https://registry.npmjs.org/grunt-css/0.3.2
npm http 304 https://registry.npmjs.org/grunt/0.3.17
npm http 304 https://registry.npmjs.org/express/3.0.5
npm http 304 https://registry.npmjs.org/grunt-contrib-copy/0.3.2
npm http 304 https://registry.npmjs.org/grunt-open/0.1.0
npm http 304 https://registry.npmjs.org/grunt-contrib-requirejs
npm http 304 https://registry.npmjs.org/grunt-contrib-clean/0.3.0
npm http 304 https://registry.npmjs.org/grunt-contrib-less/0.3.2
npm http 304 https://registry.npmjs.org/grunt-reload/0.2.0
npm http 304 https://registry.npmjs.org/grunt-smushit/0.3.8
npm http 304 https://registry.npmjs.org/grunt-usemin
npm http GET https://registry.npmjs.org/node-smushit
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/wrench
npm http GET https://registry.npmjs.org/grunt-contrib-lib
npm http GET https://registry.npmjs.org/gzip-js/0.3.1
npm http GET https://registry.npmjs.org/sqwish/0.2.0
npm http GET https://registry.npmjs.org/csslint/0.9.9
npm http GET https://registry.npmjs.org/requirejs
npm http GET https://registry.npmjs.org/grunt-lib-contrib
npm http GET https://registry.npmjs.org/websocket
npm http GET https://registry.npmjs.org/open/0.0.2
npm http GET https://registry.npmjs.org/connect
npm http GET https://registry.npmjs.org/less
npm http GET https://registry.npmjs.org/buffers/0.1.1
npm http GET https://registry.npmjs.org/http-proxy/0.8.0
npm http GET https://registry.npmjs.org/connect/2.7.1
npm http GET https://registry.npmjs.org/commander/0.6.1
npm http GET https://registry.npmjs.org/range-parser/0.0.4
npm http GET https://registry.npmjs.org/mkdirp/0.3.3
npm http GET https://registry.npmjs.org/cookie/0.0.5
npm http GET https://registry.npmjs.org/buffer-crc32/0.1.1
npm http GET https://registry.npmjs.org/fresh/0.1.0
npm http GET https://registry.npmjs.org/methods/0.0.1
npm http GET https://registry.npmjs.org/send/0.1.0
npm http GET https://registry.npmjs.org/cookie-signature/0.0.1
npm http GET https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/wrench
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/grunt-contrib-lib
npm http 304 https://registry.npmjs.org/gzip-js/0.3.1
npm http 304 https://registry.npmjs.org/csslint/0.9.9
npm http 304 https://registry.npmjs.org/requirejs
npm http 304 https://registry.npmjs.org/sqwish/0.2.0
npm http 200 https://registry.npmjs.org/node-smushit
npm WARN deprecated grunt-contrib-lib@0.3.0: renamed to grunt-lib-contrib
npm WARN package.json csslint@0.9.9 No README.md file found!
npm http GET https://registry.npmjs.org/node-smushit/-/node-smushit-0.5.1.tgz
npm http 304 https://registry.npmjs.org/grunt-lib-contrib
npm http 304 https://registry.npmjs.org/connect
npm http 304 https://registry.npmjs.org/open/0.0.2
npm http 304 https://registry.npmjs.org/less
npm http 304 https://registry.npmjs.org/buffers/0.1.1
npm http 304 https://registry.npmjs.org/websocket
npm http GET https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/crc32
npm http GET https://registry.npmjs.org/deflate-js
npm WARN package.json connect@2.3.9 No README.md file found!
npm http 304 https://registry.npmjs.org/mkdirp/0.3.3
npm http 304 https://registry.npmjs.org/connect/2.7.1
npm http 304 https://registry.npmjs.org/http-proxy/0.8.0
npm http 304 https://registry.npmjs.org/commander/0.6.1
npm http 304 https://registry.npmjs.org/range-parser/0.0.4
npm http 304 https://registry.npmjs.org/cookie/0.0.5
npm http 304 https://registry.npmjs.org/buffer-crc32/0.1.1
npm http 304 https://registry.npmjs.org/fresh/0.1.0
npm http 304 https://registry.npmjs.org/send/0.1.0
npm http 304 https://registry.npmjs.org/methods/0.0.1
npm WARN package.json methods@0.0.1 No README.md file found!
npm http 200 https://registry.npmjs.org/node-smushit/-/node-smushit-0.5.1.tgz
npm http 304 https://registry.npmjs.org/crc32
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/cookie-signature/0.0.1
npm http 304 https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/tmp
npm http GET https://registry.npmjs.org/vows
npm http GET https://registry.npmjs.org/archy
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/colors
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/deflate-js
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/colors
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/stable
npm http GET https://registry.npmjs.org/hogan.js
npm http GET https://registry.npmjs.org/fstream
npm http GET https://registry.npmjs.org/unzip/0.0.4
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/rc
npm http GET https://registry.npmjs.org/read-package-json
npm http GET https://registry.npmjs.org/tar
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/nopt
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/request

> websocket@1.0.8 install /Applications/MAMP/htdocs/fac/genesis2/node_modules/grunt-reload/node_modules/websocket
> node install.js

npm http GET https://registry.npmjs.org/mime/1.2.6
[websocket v1.0.8] Attempting to compile native extensions.
npm http 304 https://registry.npmjs.org/hogan.js
npm http 304 https://registry.npmjs.org/stable
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/colors
npm http GET https://registry.npmjs.org/connect
npm http GET https://registry.npmjs.org/dateformat/1.0.2-1.2.3
npm http GET https://registry.npmjs.org/glob-whatev
npm http GET https://registry.npmjs.org/hooker
npm http GET https://registry.npmjs.org/jshint
npm http GET https://registry.npmjs.org/nodeunit
npm http GET https://registry.npmjs.org/nopt
npm http GET https://registry.npmjs.org/prompt
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/uglify-js
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/underscore.string
npm http GET https://registry.npmjs.org/temporary
npm http GET https://registry.npmjs.org/gzip-js
npm http 304 https://registry.npmjs.org/tmp
npm http 304 https://registry.npmjs.org/vows
npm http 304 https://registry.npmjs.org/archy
npm http 304 https://registry.npmjs.org/fstream
npm http 304 https://registry.npmjs.org/read-package-json
npm http 304 https://registry.npmjs.org/unzip/0.0.4
npm http 304 https://registry.npmjs.org/rc
npm http 304 https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/tar
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/mime/1.2.6
npm http 304 https://registry.npmjs.org/nopt
npm http 304 https://registry.npmjs.org/colors
npm http 304 https://registry.npmjs.org/glob-whatev
npm http 304 https://registry.npmjs.org/dateformat/1.0.2-1.2.3
npm http 304 https://registry.npmjs.org/connect
npm http 304 https://registry.npmjs.org/hooker
npm http 304 https://registry.npmjs.org/nodeunit
npm http 304 https://registry.npmjs.org/nopt
npm http 304 https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/prompt
npm http 304 https://registry.npmjs.org/uglify-js
npm http 304 https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/underscore.string
npm http 304 https://registry.npmjs.org/temporary
npm http 304 https://registry.npmjs.org/gzip-js
npm http 200 https://registry.npmjs.org/jshint
npm http GET https://registry.npmjs.org/qs/0.4.2
npm http GET https://registry.npmjs.org/formidable/1.0.11
npm http GET https://registry.npmjs.org/crc/0.2.0
npm http GET https://registry.npmjs.org/cookie/0.0.4
npm http GET https://registry.npmjs.org/bytes/0.1.0
npm http GET https://registry.npmjs.org/send/0.0.3
npm http GET https://registry.npmjs.org/fresh/0.1.0
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/config-chain
npm http GET https://registry.npmjs.org/abbrev
npm http GET https://registry.npmjs.org/slide
npm http GET https://registry.npmjs.org/pullstream/0.0.4
npm http GET https://registry.npmjs.org/binary
npm http GET https://registry.npmjs.org/npmlog
npm http GET https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/lru-cache
[websocket v1.0.8] Native extension compilation successful!
npm http GET https://registry.npmjs.org/colors
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/pkginfo
npm http 304 https://registry.npmjs.org/cookie/0.0.4
npm http 304 https://registry.npmjs.org/bytes/0.1.0
npm http 304 https://registry.npmjs.org/crc/0.2.0
npm http 304 https://registry.npmjs.org/formidable/1.0.11
npm http 304 https://registry.npmjs.org/qs/0.4.2
npm http GET https://registry.npmjs.org/crc32
npm http GET https://registry.npmjs.org/deflate-js
npm http 304 https://registry.npmjs.org/send/0.0.3
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/fresh/0.1.0
npm http 304 https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/qs/0.5.1
npm http GET https://registry.npmjs.org/formidable/1.0.11
npm http GET https://registry.npmjs.org/package
npm http GET https://registry.npmjs.org/crc/0.2.0
npm http GET https://registry.npmjs.org/bytes/0.1.0
npm http GET https://registry.npmjs.org/pause/0.0.1
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/block-stream
npm http GET https://registry.npmjs.org/pkginfo
npm http GET https://registry.npmjs.org/winston
npm http 304 https://registry.npmjs.org/pullstream/0.0.4
npm http 304 https://registry.npmjs.org/slide
npm http 304 https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/abbrev
npm http 304 https://registry.npmjs.org/config-chain
npm http GET https://registry.npmjs.org/diff
npm http GET https://registry.npmjs.org/eyes
npm http GET https://registry.npmjs.org/cli/0.4.3
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/mime/1.2.6
npm http GET https://registry.npmjs.org/range-parser/0.0.4
npm http GET https://registry.npmjs.org/proto-list
npm http GET https://registry.npmjs.org/ini
npm http GET https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/colors
npm http 304 https://registry.npmjs.org/npmlog
npm http 304 https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/binary
npm http 304 https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/ycssmin
npm http 304 https://registry.npmjs.org/qs/0.5.1
npm http 304 https://registry.npmjs.org/pkginfo
npm http 304 https://registry.npmjs.org/crc32
npm http 304 https://registry.npmjs.org/deflate-js
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/crc/0.2.0
npm http 304 https://registry.npmjs.org/formidable/1.0.11
npm http 304 https://registry.npmjs.org/pause/0.0.1
npm http 304 https://registry.npmjs.org/bytes/0.1.0
npm http 304 https://registry.npmjs.org/package
npm http GET https://registry.npmjs.org/ansi
npm http GET https://registry.npmjs.org/over
npm http GET https://registry.npmjs.org/stream-buffers
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/diff
npm http 304 https://registry.npmjs.org/pkginfo
npm http 304 https://registry.npmjs.org/winston
npm http 304 https://registry.npmjs.org/block-stream
npm http GET https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/eyes
npm http 304 https://registry.npmjs.org/mime/1.2.6
npm http 304 https://registry.npmjs.org/range-parser/0.0.4
npm http 304 https://registry.npmjs.org/cli/0.4.3
npm http 304 https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/proto-list
npm http 304 https://registry.npmjs.org/ini
npm http 304 https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/ansi
npm http 304 https://registry.npmjs.org/ycssmin
npm http 304 https://registry.npmjs.org/over
npm http 304 https://registry.npmjs.org/stream-buffers
npm http 304 https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/sigmund
npm http GET https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/qs/0.5.1
npm http GET https://registry.npmjs.org/formidable/1.0.11
npm http GET https://registry.npmjs.org/crc/0.2.0
npm http GET https://registry.npmjs.org/cookie/0.0.4
npm http GET https://registry.npmjs.org/bytes/0.1.0
npm http GET https://registry.npmjs.org/send/0.0.4
npm http GET https://registry.npmjs.org/fresh/0.1.0
npm http GET https://registry.npmjs.org/pause/0.0.1
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/chainsaw
npm http GET https://registry.npmjs.org/buffers
npm http GET https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/glob

> lodash@0.9.2 install /Applications/MAMP/htdocs/fac/genesis2/node_modules/bower/node_modules/lodash
> node build/post-install

npm http 304 https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/tap
npm http GET https://registry.npmjs.org/eyes
npm http GET https://registry.npmjs.org/pkginfo
npm http GET https://registry.npmjs.org/loggly
npm http GET https://registry.npmjs.org/stack-trace
npm http 304 https://registry.npmjs.org/bytes/0.1.0
npm http 304 https://registry.npmjs.org/send/0.0.4
npm http 304 https://registry.npmjs.org/fresh/0.1.0
npm http 304 https://registry.npmjs.org/cookie/0.0.4
npm http 304 https://registry.npmjs.org/formidable/1.0.11
npm http 304 https://registry.npmjs.org/crc/0.2.0
npm http 304 https://registry.npmjs.org/qs/0.5.1
npm http 304 https://registry.npmjs.org/pause/0.0.1
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/buffers
npm http 304 https://registry.npmjs.org/chainsaw
npm http 304 https://registry.npmjs.org/tap
npm http 304 https://registry.npmjs.org/eyes
npm http 304 https://registry.npmjs.org/loggly
npm http 304 https://registry.npmjs.org/stack-trace
npm http 304 https://registry.npmjs.org/pkginfo
npm http GET https://registry.npmjs.org/mime/1.2.6
npm http GET https://registry.npmjs.org/range-parser/0.0.4
npm http GET https://registry.npmjs.org/traverse
npm http 304 https://registry.npmjs.org/mime/1.2.6
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/range-parser/0.0.4
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/timespan
npm http GET https://registry.npmjs.org/difflet
npm http GET https://registry.npmjs.org/deep-equal
npm http GET https://registry.npmjs.org/buffer-equal
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/slide
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/nopt
npm http GET https://registry.npmjs.org/runforcover
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/traverse
npm http 304 https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/difflet
npm http 304 https://registry.npmjs.org/timespan
npm WARN prefer global bower@0.6.8 should be installed with -g

> bower@0.6.8 postinstall /Applications/MAMP/htdocs/fac/genesis2/node_modules/bower
> node cleanup

npm http 304 https://registry.npmjs.org/deep-equal
npm http 304 https://registry.npmjs.org/buffer-equal
npm http 304 https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/slide
npm http GET https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/runforcover
npm http 304 https://registry.npmjs.org/nopt
npm http GET https://registry.npmjs.org/bunker
npm http GET https://registry.npmjs.org/abbrev
npm http GET https://registry.npmjs.org/traverse
npm http GET https://registry.npmjs.org/charm
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/charm
npm http 304 https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/bunker
npm http 304 https://registry.npmjs.org/traverse
npm http 304 https://registry.npmjs.org/abbrev
npm http GET https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/sigmund
npm http GET https://registry.npmjs.org/burrito
npm http 304 https://registry.npmjs.org/burrito
npm http 304 https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/traverse
npm http GET https://registry.npmjs.org/uglify-js
npm http 304 https://registry.npmjs.org/traverse
npm http 304 https://registry.npmjs.org/uglify-js
npm WARN prefer global grunt@0.3.17 should be installed with -g
npm WARN cannot run in wd genesis-skeleton@0.0.1 bower install (wd=/Applications/MAMP/htdocs/fac/genesis2)
grunt-usemin@0.1.2 node_modules/grunt-usemin

grunt-angular-templates@0.1.3 node_modules/grunt-angular-templates

grunt-contrib-copy@0.3.2 node_modules/grunt-contrib-copy
└── grunt-lib-contrib@0.3.1

grunt-open@0.1.0 node_modules/grunt-open
└── open@0.0.2

grunt-contrib-clean@0.3.0 node_modules/grunt-contrib-clean
├── grunt-contrib-lib@0.3.0
└── rimraf@2.0.3 (graceful-fs@1.1.14)

grunt-css@0.3.2 node_modules/grunt-css
├── sqwish@0.2.0
├── csslint@0.9.9
└── gzip-js@0.3.1 (crc32@0.2.2, deflate-js@0.2.2)

grunt-contrib-requirejs@0.3.4 node_modules/grunt-contrib-requirejs
├── grunt-lib-contrib@0.3.1
└── requirejs@2.1.3

grunt-smushit@0.3.8 node_modules/grunt-smushit
├ââ wrench@1.4.4
└── node-smushit@0.5.1 (optimist@0.3.5)

express@3.0.5 node_modules/express
├── methods@0.0.1
├── buffer-crc32@0.1.1
├── cookie@0.0.5
├── range-parser@0.0.4
├── fresh@0.1.0
├── cookie-signature@0.0.1
├── commander@0.6.1
├── debug@0.7.0
├── mkdirp@0.3.3
├── send@0.1.0 (mime@1.2.6)
└── connect@2.7.1 (bytes@0.1.0, pause@0.0.1, crc@0.2.0, formidable@1.0.11, qs@0.5.1)

grunt-reload@0.2.0 node_modules/grunt-reload
├── buffers@0.1.1
├── websocket@1.0.8
├── connect@2.3.9 (fresh@0.1.0, cookie@0.0.4, bytes@0.1.0, crc@0.2.0, qs@0.4.2, debug@0.7.0, formidable@1.0.11, send@0.0.3)
└── http-proxy@0.8.0 (colors@0.6.0-1, pkginfo@0.2.3, optimist@0.2.8)

grunt-contrib-less@0.3.2 node_modules/grunt-contrib-less
├── grunt-lib-contrib@0.3.1
└── less@1.3.3 (ycssmin@1.0.1)

bower@0.6.8 node_modules/bower
├── stable@0.1.3
├── archy@0.0.2
├── colors@0.6.0-1
├ââ semver@1.1.2
├── tmp@0.0.16
├── mkdirp@0.3.4
├── async@0.1.22
├── rimraf@2.0.3 (graceful-fs@1.1.14)
├── nopt@2.0.0 (abbrev@1.0.4)
├── fstream@0.1.21 (inherits@1.0.0, graceful-fs@1.1.14)
├── tar@0.1.14 (inherits@1.0.0, block-stream@0.0.6)
├── rc@0.0.6 (config-chain@0.3.3, optimist@0.3.5)
├── read-package-json@0.1.12 (graceful-fs@1.1.14, lru-cache@2.0.4, slide@1.1.3, npmlog@0.0.2)
├── vows@0.6.4 (eyes@0.1.8, diff@1.0.4)
├── glob@3.1.16 (inherits@1.0.0, graceful-fs@1.1.14, minimatch@0.2.9)
├── request@2.11.4
├── hogan.js@2.0.0
├── lodash@0.9.2
└── unzip@0.0.4 (pullstream@0.0.4, binary@0.3.0)

grunt@0.3.17 node_modules/grunt
├── dateformat@1.0.2-1.2.3
├── colors@0.6.0-1
├── semver@1.0.14
├── async@0.1.22
├── hooker@0.2.3
├── nopt@1.0.10 (abbrev@1.0.4)
├── underscore@1.2.4
├── underscore.string@2.1.1
├── temporary@0.0.5 (package@1.0.1)
├ââ gzip-js@0.3.1 (crc32@0.2.2, deflate-js@0.2.2)
├── uglify-js@1.3.4
├── glob-whatev@0.1.8 (minimatch@0.2.9)
├── connect@2.4.6 (fresh@0.1.0, pause@0.0.1, bytes@0.1.0, cookie@0.0.4, crc@0.2.0, debug@0.7.0, formidable@1.0.11, send@0.0.4, qs@0.5.1)
├── prompt@0.1.12 (pkginfo@0.3.0, winston@0.5.11)
├── jshint@0.9.1 (minimatch@0.0.5, cli@0.4.3)
└── nodeunit@0.7.4 (tap@0.4.0)
Matt-Millers-MacBook-Pro-2:genesis2 mmiller001$ 
Matt-Millers-MacBook-Pro-2:genesis2 mmiller001$ 
Matt-Millers-MacBook-Pro-2:genesis2 mmiller001$ npm install

> genesis-skeleton@0.0.1 install /Applications/MAMP/htdocs/fac/genesis2
> bower install

bower cloning git://github.com/mgcrea/angular-strap.git
bower cached git://github.com/mgcrea/angular-strap.git
bower fetching angular-strap
bower cloning git://github.com/twitter/bootstrap.git
bower cached git://github.com/twitter/bootstrap.git
bower fetching bootstrap
bower cloning git://github.com/Modernizr/Modernizr.git
bower cached git://github.com/Modernizr/Modernizr.git
bower fetching modernizr
bower checking out angular-strap#v0.6.2
bower copying /Users/mmiller001/.bower/cache/angular-strap/dc1266854d5427e943850153cd3ca66c
bower checking out modernizr#v2.6.2
bower checking out bootstrap#v2.2.2
bower copying /Users/mmiller001/.bower/cache/modernizr/9e3143e153f397b3c7d7da78376adc78
bower copying /Users/mmiller001/.bower/cache/bootstrap/c1ee45ee19795a66de4a0c45758fe0b1
bower cloning git://github.com/components/jquery.git
bower cached git://github.com/components/jquery.git
bower fetching jquery
bower checking out jquery#1.8.3
bower copying /Users/mmiller001/.bower/cache/jquery/cf68c4c4e7507c8d20fee7b5f26709d9
bower cloning git://github.com/components/jquery.git
bower cached git://github.com/components/jquery.git
bower fetching jquery
bower checking out jquery#1.8.3
bower copying /Users/mmiller001/.bower/cache/jquery/cf68c4c4e7507c8d20fee7b5f26709d9
bower installing modernizr#2.6.2
bower installing bootstrap#2.2.2
bower installing jquery#1.8.3
bower installing angular-strap#0.6.2
Matt-Millers-MacBook-Pro-2:genesis2 mmiller001$

**Comment by ericclemmons** [comment]
I "snipped" your comment so the main parts are visible, without the excess.  I hope you don't mind (everything snipped was normal npm output).

I'm curious why you're doing a `sudo npm install` first, then followed by a regular `npm install`.  From a blank project, does `npm install` not work as expected?

**Comment by ericclemmons** [comment]
Hmm, I did the following...

``` sh
$ npm remove -g grunt grunt-cli bower
$ git clean -fdx .
$ npm install
$ grunt server
Failed, because grunt could not be found
$ ./node_modules/.bin/grunt server
Local development server started on 3000
```

So it looks like we should probably recommend `npm install -g grunt-cli bower`, just because those are two primary dependencies (besides node+npm), but still no closer to knowing why it's failing for @facultymatt!

**Comment by facultymatt** [comment]
@ericclemmons thanks for cleaning up the comment. 

As for sudo, this is usually required on my setup because I get an error (something along the lines of permission denied) without it. Not sure why, likely goes back to the install of NodeJS I did (and I haven't updated recently) (although does node update itself?)

Interesting enough, I shared this with a co-worker and they had a different bower issue. 
- First time install of NodeJS (Jan 25th) 
- Download of Genesis-skeleton repo and unzip
- Run `npm install` and it successfully installed components...
  *\* However, they were not installed in the repo folder. In fact, not sure where they have gone. 
  *\* Re-installed bower using `npm bower install -g` - not sure if this was before or after the missing components issue. 

This leads me to believe the issue I was having might be a bower issue, and not related to genesis.

What do you think? 
-Matt

**Comment by ericclemmons** [comment]
Perhaps!  It really is a shame bower doesn't even tell you _where_ files are installed, just that they are.  It's up to you to find out where =/

I removed `.bowerrc`, so they should be in the project root now...
