### ISSUE TITLE
JS Errors and empty guide page on iOS

### ISSUE THREAD

**Issue by facultymatt** [ericclemmons/genesis-skeleton#62]
Hello guys, awesome work so far! Was just checking out the new guide on my iPhone and noticed a weird bug, to replicate: 
- visit genesis-skeleton.com on your iDevice
- navigate to the guide page
- click the issues link (likely works with any link that takes you to a new page) 
- press the back button
- Guide page is empty and 2 errors are logged. 

See the attached screen shots for the errors. Note I hit forward and back twice so there are 4 errors, but each event seems to log 2. 

-Matt
![photo](https://f.cloud.github.com/assets/1406258/109684/62ed3b3c-6a8f-11e2-91a1-4fc1cf3d1058.PNG)

**Comment by ericclemmons** [comment]
I'll look into it!

**Comment by ericclemmons** [comment]
I'm redoing the docs to be something simpler I can actually maintain.
