### ISSUE TITLE
[FEATURE] socket.io

### ISSUE THREAD

**Issue by ericclemmons** [ericclemmons/genesis-skeleton#78]
It's really useful for pushing data to the client, so might as well make it available by default.

I'll leave this here:

> http://socket.io/
> https://github.com/btford/angular-socket-io-seed

**Comment by simalexan** [comment]
Great!

**Comment by ericclemmons** [comment]
Remove Heroku deployment default.

**Comment by ericclemmons** [comment]
I think this is a bit out of the scope of this project...
