### ISSUE TITLE
How to handle templateUrl in directives. 

### ISSUE THREAD

**Issue by facultymatt** [ericclemmons/genesis-skeleton#79]
I just tried making a directive with templateUrl instead of including the template: <html> in the directive itself. Not having much luck... it occurred to me this might not work with how genesis combines partials/template files? 

Any suggestions? Thanks!

**Comment by ericclemmons** [comment]
Alrighty, let me change [issueDirective.js](https://github.com/ericclemmons/genesis-skeleton/blob/master/src/client/app/js/directives/issuesDirective.js) to use `templateUrl` and I'll straighten 'er out!

Ideally it should work with and without `ngtemplates`...

**Comment by ericclemmons** [comment]
What's your folder layout for partials & templates for directives?  Do they live side-by-side, or in separate folders?

**Comment by facultymatt** [comment]
I was trying it a few ways: a.) having a separate templates folder b.) inside the partials folder and c.) sprinkled throughout js folder, grouped with js files. See https://github.com/angular-app/angular-app/tree/master/client/src/common/security/login for an example. 

I tend to like option c, which seems best for keeping things organized. 

Interestingly I noticed that regardless of where you put .tpl files, grunt seems to correctly complete them together in the templates.js file... 

For example, my dist/templates.js file looks like this: 

```
$templateCache.put("app/js/services/loginForm.tpl.html",
...
);

$templateCache.put("app/js/services/toolbar.tpl.html",
...
);

$templateCache.put("app/partials/error/404.html",
...
);
```

There must be an angularjs way to load a template by its variable name, looking into this now...

**Comment by ericclemmons** [comment]
Check out #80.  I tried both `app/js/directives/issues.html` (to accompany `app/js/directives/issuesDirective.js`) and what you see now `app/partials/issues.html` and they all work.

The thing is, `/src/client/**.html` is both copied to `/dist/...` and compiled with the `ngtemplates.app.base` prefix removed from the path, so you _should_ be able to put it anywhere under `/src/client` and it should able available both publicly via URL and put into `dist/app.templates.js` or whatever...

**Comment by facultymatt** [comment]
This looks good. Got something similar working on my end. Problem was that I have the path to the templates wrong... I forgot the "app/" prefix. 

Thanks for jumping on this. Looks good to merge!
