### ISSUE TITLE
Static Restructure

### ISSUE THREAD

**Issue by ericclemmons** [ericclemmons/genesis-skeleton#95]
@kwhitley Hey, I was thinking.  I personally don't like having `_client` & all of that fancy stuff polluting the folder structure.

I say keep `_bin` & `_server`, because they are never meant to be touched.

But merge all of `_client` into the root, so that all Gruntfile does is just compile the `.min.css` and `.min.js`.  Savvy?

**Comment by ericclemmons** [comment]
@kwhitley Hello?

**Comment by kwhitley** [comment]
We talked about this! If it makes deploying easier then sure why not, but otherwise it's nice having a git ignorable folder for build output...

**Comment by ericclemmons** [comment]
But in this case, the build output is the ROOT of the project, which you can't ignore.  So, I'm wondering why keep the `client` folder at all then?

**Comment by kwhitley** [comment]
because the contents of client is never touched, at least keeping your code
clean and separate from build output/dirty files!

~
Kevin R. Whitley
@ kwhitley.com

**Comment by ericclemmons** [comment]
I'm thinking of reverting a lot of my changes here & instead keeping the `build` folder.  Perhaps the best way to handle a static site is to simply document it using my prior work:

> https://github.com/ericclemmons/ericclemmons.github.io/blob/29608775303c1c02ae02d73dfcfc82dc61948af8/bin/publish

Basically, always make the `build` directory the `gh-pages` branch...

**Comment by kwhitley** [comment]
Certainly would help keep things separated...

~
Kevin R. Whitley
@ kwhitley.com

**Comment by ericclemmons** [comment]
After looking at this again, I think I'd rather just write a guide saying:

> Here, run everything as normal, then just go into `build/`, do a `git init`, and force push using the script provided above

That effectively works, it's simple, and you don't lose the awesome structure or end up with headaches between branches.

**Comment by ericclemmons** [comment]
@kwhitley This is kind of how we discussed today.  I'm going to come back to this when there is time...
