### ISSUE TITLE
Live reload fails with Inotify on ubuntu

### ISSUE THREAD

**Issue by rehno-lindeque** [ericclemmons/genesis-skeleton#97]
Hi, on ubuntu (ver 13.04) live reload fails in the `regarde` task because the system limit for inotify watchers is reached. (The same issue occurs here https://github.com/yeoman/yeoman/issues/717)

There's a temporary fix mentioned there, which is to use the command 

`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

Thanks!

**Comment by ericclemmons** [comment]
Thanks for letting me know about the fix!  I'm using `grunt-contrib-watch` now, but this belongs in the docs...

**Comment by rehno-lindeque** [comment]
No problem!

**Comment by ericclemmons** [comment]
Update documentation with this fix...
