### ISSUE TITLE
Browser tests fails to run without ng-app="app" on <body> tag, adding this tag causes app to be started twice!  

### ISSUE THREAD

**Issue by facultymatt** [ericclemmons/genesis-skeleton#99]
Genesis launches the app instance using the following method: 

```
<script>
  angular.bootstrap(document.documentElement, ['app']);
</script>
```

The current master version also includes the following body tag: 

```
<body ng-app="app">
```

This is causing the app to start twice! You can verify this by loggin from a controller. You'll see the log twice. My first solution was to remove the ng-app="app" from the body tag, however this caused issues with the browser tests at http://localhost:3000/app/test/e2e/runner.html. They never started. 

The second solution was to remove the '<script></script>' method of starting the app. The app is still started by the body tag AND the browser tests work. However I'm not sure this isn't going to break something else. 

@ericclemmons can you double check this solve and update master if this solve works? 

Thanks! Keep up the good work.

**Comment by ericclemmons** [comment]
I think now I recommend using `ng-app` instead of manually bootstrapping, since that's the "angular way".  Manual bootstrapping was being done because, at the time, I was using RequireJS and that fit in with the `main.js` mantra.
